In [ ]:
import numpy as np

np.random.seed(42)
ages = np.random.randint(19,39,20)

print("Ages:", ages)

print("Shape:", ages.shape)
print("Size:", ages.size)
print("Data type:", ages.dtype)

ages_matrix = ages.reshape(4,5)
print("Ages Matrix:\n", ages_matrix)

mean_age = np.mean(ages)
print("Mean Age:", mean_age)
median_age = np.median(ages)
print("Median Age:", median_age)
std_age = np.std(ages)
print("Standard Deviation of Age:", std_age)

q75, q25 = np.percentile(ages, [75 ,25])
iqr = q75 - q25
print("Interquartile Range (IQR):", iqr)

ages_above_30 = ages[ages > 30]
print("Ages above 30:", ages_above_30)

ages[ages < 21] = 21
print("Ages after replacing values below 21 with 21:", ages)


Ages: [25 38 33 29 26 25 37 29 29 22 26 21 20 30 24 20 19 30 30 35]
Shape: (20,)
Size: 20
Data type: int32
Ages Matrix:
 [[25 38 33 29 26]
 [25 37 29 29 22]
 [26 21 20 30 24]
 [20 19 30 30 35]]
